name: 游냍 Reportar un Bug
description: Informar un error no relacionado con la seguridad en CodericLatam
labels: ["kind/bug", "bug", "status/triage"]
assignees:
  - neftaliyagua
body:
  - type: textarea
    attributes:
      label: Describe el error
      description: Proporcione una descripci칩n clara y concisa de cu치l es el problema.
    validations:
      required: true
  - type: input
    attributes:
      label: Versi칩n
      description: 쯈u칠 versi칩n de la Aplicaci칩n est치s ejecutando?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Comportamiento esperado
      description: Describa el comportamiento esperado de forma clara y concisa.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Comportamiento real
      description: Describe el comportamiento real de forma clara y concisa.
    validations:
      required: false
  - type: textarea
    attributes:
      label: 쮺칩mo se reproduce?
      description: Proporcione pasos claros y concisos para reproducir el problema.
    validations:
      required: false
  - type: textarea
    attributes:
      label: 쮸lgo m치s?
      description: 쮼nlaces? Referencias? 춰Cualquier cosa que nos brinde m치s contexto sobre el problema que ha encontrado!
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: C칩digo de Conducta
      description: Al enviar esta incidencia, acepta seguir nuestro [C칩digo de conducta](https://codericlatam.github.io/docs/codigo_de_conducta.html)
      options:
        - label: Acepto seguir el C칩digo de conducta de este proyecto.
          required: true
