name: З Solicitud de mejora
description: Solicitar una mejora de una funci贸n existente
labels: ["kind/enhancement", "enhancement", "status/triage"]
assignees:
  - neftaliyagua
body:
  - type: textarea
    attributes:
      label: Descripci贸n
      description: Describe la mejora a alto nivel.
    validations:
      required: true
  - type: input
    attributes:
      label: Discusi贸n
      description: |
        Si ha habido una discusi贸n sobre la mejora, proporcione un enlace a la discusi贸n.

        Tenga en cuenta que las mejoras m谩s importantes deben discutirse a trav茅s de [Tormenta de ideas](https://github.com/orgs/CodericLatam/discussions/categories/tormenta-de-ideas).
    validations:
      required: false
  - type: textarea
    attributes:
      label: Motivaci贸n
      description: Describa por qu茅 se debe agregar la caracter铆stica.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Detalles
      description: 驴M谩s detalles? 驴Ideas de implementaci贸n? 隆Cualquier cosa que nos d茅 m谩s contexto sobre la mejora que est谩s proponiendo!
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: C贸digo de Conducta
      description: Al enviar esta incidencia, acepta seguir nuestro [C贸digo de conducta](https://codericlatam.github.io/docs/codigo_de_conducta.html)
      options:
        - label: Acepto seguir el C贸digo de conducta de este proyecto.
          required: true
